services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/rickAndMorty
      - node_modules:/app/rickAndMorty/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  node_modules: